// <auto-generated />
using System;
using HutechNovel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HutechNovel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506105358_AddTongSoSaoToTruyen")]
    partial class AddTongSoSaoToTruyen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HutechNovel.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaiDatCoChu")
                        .HasColumnType("int");

                    b.Property<string>("CaiDatFontChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaiDatMauNen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KhaiSinh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("NgayDiemDanhCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("SoChuongDaDoc")
                        .HasColumnType("int");

                    b.Property<int>("SoPhutDaDoc")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VeDaySach")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HutechNovel.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int?>("MaBinhLuanCha")
                        .HasColumnType("int");

                    b.Property<int?>("MaChuong")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaBinhLuanCha");

                    b.HasIndex("MaChuong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("HutechNovel.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CheDoBaoTri")
                        .HasColumnType("bit");

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTaSEO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenWebsite")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThongBaoToanCuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeSEO")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhHeThongs");
                });

            modelBuilder.Entity("HutechNovel.Models.Chuong", b =>
                {
                    b.Property<int>("MaChuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuong"));

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHenGio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoChuong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuong");

                    b.HasIndex("MaTruyen", "SoChuong")
                        .IsUnique();

                    b.ToTable("Chuongs");
                });

            modelBuilder.Entity("HutechNovel.Models.DanhDau", b =>
                {
                    b.Property<int>("MaDanhDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhDau"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhDau");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("DanhDaus");
                });

            modelBuilder.Entity("HutechNovel.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("HutechNovel.Models.DayTruyen", b =>
                {
                    b.Property<int>("MaDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDay"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDay");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("DayTruyens");
                });

            modelBuilder.Entity("HutechNovel.Models.LichSuDoc", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianDoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaChuong");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuDocs");
                });

            modelBuilder.Entity("HutechNovel.Models.LuotXem", b =>
                {
                    b.Property<int>("MaLuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuotXem"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianXem")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLuotXem");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("LuotXems");
                });

            modelBuilder.Entity("HutechNovel.Models.NoiDungChuong", b =>
                {
                    b.Property<int>("MaNoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNoiDung"));

                    b.Property<int>("LoaiNoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNoiDung");

                    b.HasIndex("MaChuong", "LoaiNoiDung")
                        .IsUnique();

                    b.ToTable("NoiDungChuongs");
                });

            modelBuilder.Entity("HutechNovel.Models.TacGia", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("HutechNovel.Models.The", b =>
                {
                    b.Property<int>("MaThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThe"));

                    b.Property<string>("TenThe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThe");

                    b.HasIndex("TenThe")
                        .IsUnique();

                    b.ToTable("Thes");
                });

            modelBuilder.Entity("HutechNovel.Models.TheoDoiTruyen", b =>
                {
                    b.Property<int>("MaTheoDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheoDoi"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTheoDoi");

                    b.HasIndex("MaTruyen");

                    b.HasIndex("MaNguoiDung", "MaTruyen")
                        .IsUnique();

                    b.ToTable("TheoDoiTruyens");
                });

            modelBuilder.Entity("HutechNovel.Models.Truyen", b =>
                {
                    b.Property<int>("MaTruyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTruyen"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiemDanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<double>("DiemTrending")
                        .HasColumnType("float");

                    b.Property<int>("MaTacGia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDangId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TongLuotXem")
                        .HasColumnType("int");

                    b.Property<int>("TongSoChuong")
                        .HasColumnType("int");

                    b.Property<int>("TongSoSao")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaTruyen");

                    b.HasIndex("MaTacGia");

                    b.HasIndex("NguoiDangId");

                    b.ToTable("Truyens");
                });

            modelBuilder.Entity("HutechNovel.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuThich"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTruyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaYeuThich");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTruyen");

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheTruyen", b =>
                {
                    b.Property<int>("ThesMaThe")
                        .HasColumnType("int");

                    b.Property<int>("TruyensMaTruyen")
                        .HasColumnType("int");

                    b.HasKey("ThesMaThe", "TruyensMaTruyen");

                    b.HasIndex("TruyensMaTruyen");

                    b.ToTable("TheTruyen");
                });

            modelBuilder.Entity("HutechNovel.Models.BinhLuan", b =>
                {
                    b.HasOne("HutechNovel.Models.BinhLuan", "BinhLuanCha")
                        .WithMany("BinhLuanCons")
                        .HasForeignKey("MaBinhLuanCha")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HutechNovel.Models.Chuong", "Chuong")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BinhLuanCha");

                    b.Navigation("Chuong");

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.Chuong", b =>
                {
                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("Chuongs")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.DanhDau", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("DanhDaus")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("DanhDaus")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.DanhGia", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.DayTruyen", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("DayTruyens")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("DayTruyens")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.LichSuDoc", b =>
                {
                    b.HasOne("HutechNovel.Models.Chuong", "Chuong")
                        .WithMany("LichSuDocs")
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("LichSuDocs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuong");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HutechNovel.Models.LuotXem", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("LuotXems")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("LuotXems")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.NoiDungChuong", b =>
                {
                    b.HasOne("HutechNovel.Models.Chuong", "Chuong")
                        .WithMany("NoiDungChuongs")
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuong");
                });

            modelBuilder.Entity("HutechNovel.Models.TheoDoiTruyen", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("TheoDoiTruyens")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("TheoDoiTruyens")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("HutechNovel.Models.Truyen", b =>
                {
                    b.HasOne("HutechNovel.Models.TacGia", "TacGia")
                        .WithMany("Truyens")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDang")
                        .WithMany("TruyenDaDangs")
                        .HasForeignKey("NguoiDangId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDang");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("HutechNovel.Models.YeuThich", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", "NguoiDung")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", "Truyen")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Truyen");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HutechNovel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheTruyen", b =>
                {
                    b.HasOne("HutechNovel.Models.The", null)
                        .WithMany()
                        .HasForeignKey("ThesMaThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HutechNovel.Models.Truyen", null)
                        .WithMany()
                        .HasForeignKey("TruyensMaTruyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HutechNovel.Models.ApplicationUser", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DanhDaus");

                    b.Navigation("DanhGias");

                    b.Navigation("DayTruyens");

                    b.Navigation("LichSuDocs");

                    b.Navigation("LuotXems");

                    b.Navigation("TheoDoiTruyens");

                    b.Navigation("TruyenDaDangs");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("HutechNovel.Models.BinhLuan", b =>
                {
                    b.Navigation("BinhLuanCons");
                });

            modelBuilder.Entity("HutechNovel.Models.Chuong", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("LichSuDocs");

                    b.Navigation("NoiDungChuongs");
                });

            modelBuilder.Entity("HutechNovel.Models.TacGia", b =>
                {
                    b.Navigation("Truyens");
                });

            modelBuilder.Entity("HutechNovel.Models.Truyen", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("Chuongs");

                    b.Navigation("DanhDaus");

                    b.Navigation("DanhGias");

                    b.Navigation("DayTruyens");

                    b.Navigation("LuotXems");

                    b.Navigation("TheoDoiTruyens");

                    b.Navigation("YeuThichs");
                });
#pragma warning restore 612, 618
        }
    }
}
